name: Testing

on:
  push:
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          cache-suffix: main-py${{ matrix.python-version }}
          enable-cache: true
      - name: Run tox
        run: |
          uv tool install tox --with tox-gh-actions --with tox-uv --python ${{ matrix.python-version }}
          tox -- -vv --durations=0
